"""create initial tables

Revision ID: 97e220eb88b9
Revises: 
Create Date: 2026-06-23 16:31:27.588148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e220eb88b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=True),
    sa.Column('pattern_id', sa.String(), nullable=True),
    sa.Column('problem_name', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_entries')
    op.drop_table('users')
    op.drop_table('patterns')
    op.drop_table('activities')
    # ### end Alembic commands ###
